language: python
dist: xenial
python:
- 3.7
env:
  matrix:
  - AWS_DEFAULT_REGION=us-west-2 BOTO_CONFIG=/dev/null AWS_XRAY_SDK_ENABLED=false
    USER_TABLE=testing
  - secure: cFfajus1jMxB61rk5B7ocl7cdMJgRg2wEyaMxJ/jSKbDUL6ldd+P8eccslAazpUX3DaKMr/0B6i62vDlNM27K7AnufsfKxqnHusFArk8IWMj9XThhwd45OT8USrfGJBevxYMAHWotzI8C5oAYyf91R2HRw42cjI2tet3KlUoSk1AmXJYJEY6Nb12A0tHFHUoCwtu2Z+GWsJnb2rlOEGlPHaDCpR9OZLOAVMMZAfYFGob9cfGL/jK7CzJSHydkm3bNEpFjD75p7BklX98kayGRyhaMmAa5qGr8997QkgHnP011HQcv/jSbjqmX192UVmW4iW3QnXw8cwvzhkfDNI5FeThgLr44jE2YLTGZHGgZxJ8DyCxntpgrlMi7nFSFmmV3uvw8yUBXm0HVBjHak0DEfn6ohax1d7IEuZAmwqZh2EfhbbIKDBuXpbKH0pHYqSL9PKKLnJyyzUYYl6CI9QLN8fyGNeDDOrzIsNjRsR1PMFvTZH2yxxQGUJllSKpEW02Wqxn6x4KeIrowjs75wMexQnpAat8vJE2sS7yGXmM9Afh+o7UJqTAJByiP3CnJMXShI5BVCONQklmQWh4Czsa9PACMOznk5yXn3LYSmlM5675kP7qXhLRmEmSr3XpgpYjrBYsfo3LoYljcOuO6MM3vRw2MiIkqBQr4iUqhQSlmqs=
  STRIPE_API_KEY:
    secure: X0FRN20rk1euH3pL2NyhVpPXnswxz+ft+mpzIGK5lMH5pcVx+ApShJ0lBNzKl2gL9Kd4HpudQZ+Y0BQF8GeOupAct1LQfHsCOfPpPlJYfTFPsljVZwPwSJz9U2OQ30nfUyyaFF2ZY/x/7YoMw8bZpeMzglfkmCMUWJ62jHjvktPlHKlnU484E3NAP/Z06oSuAZPvoDkPU/Mzkt8PtC9YiBg0tBem7irW3DHa64xAtvTlv9yV5vu06kaAPCRisNHgxHTnvQZ5t1b2RoeLKAKEr9AKX7R1La67g7AYfyAQGqQHAUo6XHY20azNaMywkkbSMwKbWnM6z5jZG8HJZN1JtdDz+MWCISRajQhMkBZms6VB/W4FR3RsHrYXum6ikRqULI75zZEbBR+BEYnwEG6LCz/ccmIPD361m8P8bSZA4c6AH9DjBZbeqdo63NvotAtUyGe58ub1yYE5tZOutp/EaAFDRi3NM8ekz765zHesJ8uMrc6MoFeDSJp21uCg4y35aaNQ6TY9wO7Yb7BCfKWvAZeO1WeX18biM2whybNlyG/eHN6iqbP1QQkP3gfMyPgtCtTG8R2l/VydlxUyM+jBgS/N/CvPHnDLxuJKOcnPC/MS9JGX1XqlO/iXZGoiU83Hn09b27+1VqWSuIKAoabVEmnwMzhFYiK4aS+RerCxMGA=
before_install:
- sudo rm -f /etc/boto.cfg
- pip install -r requirements.txt
- npm install -g dynalite
- npm install -g kinesalite
script:
- export BOTO_CONFIG=/dev/null
- mkdir ~/.aws
- |
  cat << EOF > ~/.aws/credentials
  [default]
  aws_access_key_id=ABCDEFG
  aws_secret_access_key=ABCDEFG
  EOF
- |
  cat << EOF > ~/.aws/config
  [default]
  output=json
  region=us-west-2
  EOF
- doit test
