language: python
dist: xenial
python:
- 3.7
env:
  AWS_DEFAULT_REGION: us-west-2
  BOTO_CONFIG: /dev/null
  AWS_XRAY_SDK_ENABLED: false
  USER_TABLE: testing
  secure: "Mv8HcQ/SUWy6SgJ163k9J+0W6JjzzFmXVhOjr1iFvTuCEapKH42HR5t9eJeDvyd10x0t6ejNlKHPkK2fVynaF8A66f8TPWZw4TypwqlOssaIBRWM2c91Y2h/zcgJnZFT7eatP+8G9rb1rjlxs8R0Eu3xKnX6swjO7jcp0hLJFh2dBz682Qqp8A/QLtdnZGOorTcXEsxa5n5xpd1nz3y5LbaftsfW3dqFSD3n1aFrv7cMcSZGIAmusIkO1DIL9JuXG4ON4lF8d+5vibfWO2WkuCpqF/e1x1Lnz/5jddeGfuFs4hs3ZE8HPLskUaEYEil59nFywI4v5GjhgHj00LEpNnIMBfqewP3tlWRrh0/ZM1tXZQO3pJBeFevnjlydkfVbPKGoJaaQYtaHevIJVycyW8Pns7B4hh1Y77c2FmQyd8jF/aBVUjHlYxHsGyrscHWUjI/Jlva60nG0lQbx10RQjLtgvUr01vK274XaNU3SVoAWHmi0FxSBKPXiBtPDPz9R7o2pDt2gj0VHzbkaWRwmfsjWHQ5dWgrnU8g/ulII621+fhCuP60XI2rNXX7Pe2hl08WUi1sicHNlHhv3k60vKqdnrK/4OyN+OrIR4VGXXc+ehXSHiYWOlv2qr0vn0njwQyNb4vcGaRDmTeryvalMnMfRkBEO7mZG4jeAKCshxMg="
before_install:
- sudo rm -f /etc/boto.cfg
- pip install -r requirements.txt
- npm install -g dynalite
- npm install -g kinesalite
script:
- export BOTO_CONFIG=/dev/null
- mkdir ~/.aws
- |
  cat << EOF > ~/.aws/credentials
  [default]
  aws_access_key_id=ABCDEFG
  aws_secret_access_key=ABCDEFG
  EOF
- |
  cat << EOF > ~/.aws/config
  [default]
  output=json
  region=us-west-2
  EOF
- env | grep STRIPE_API_KEY | head -c 22
- doit test
